### ISSUE TITLE
환경세팅 관련 문의드립니다.

### ISSUE THREAD

**Issue by HyunCello** [SeunghwanByun/KITTI_PROJECTION#1]
KITTI 데이터셋의 Lidar 파일을 2D로 Projection을 하고 싶어 깃허브에서 코드를 찾아 봤는데요
C++ 코드가 선생님 자료가 유일해서 돌려보려고 했는데
환경설정이 다른 것인지 빌드가 되지 않습니다.
코드를 확인해보니 윈도우에서 돌리신것 같은데 저의 환경은 우분투 기반이라 OpenCV 및 다른 헤더파일이 작동하지 않는 것 같습니다.
혹시 환경이 어떻게 되셨는지 알려주시면 너무 감사할 것 같습니다.

**Comment by SeunghwanByun** [comment]
안녕하세요! 문의주셔서 감사드립니다.
 
일단, 말씀하신 것 처럼 KITTI_PROJECTION 리포지토리에 있는 윈도우 상에서 돌아가는 것을 목적으로 작성하였습니다.
코드를 보시면, 파일 입출력하는 함수를 사용하기 위해 Windows.h 헤더를 사용하고 있어서 작동이 안되는 것으로 판단됩니다.
파일 입출력 부분을 우분투에 맞는 헤더 함수로 바꾸시고, 함수 또한 그에 맞게 바꿔서 사용하시면 나머지 OpenCV와 같은 라이브러리를 잘 설치를 하셨다면 문제없이 돌아갈 것 같습니다.
시도해보시면 좋을 것 같습니다.
 
감사합니다.
 
-----Original Message-----
From: "Yu Hyun, ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2021-04-25 (일) 01:53:23 (GMT+09:00)
Subject: [SeunghwanByun/KITTI_PROJECTION] 환경세팅 관련 문의드립니다. (#1)
 
KITTI 데이터셋의 Lidar 파일을 2D로 Projection을 하고 싶어 깃허브에서 코드를 찾아 봤는데요
C++ 코드가 선생님 자료가 유일해서 돌려보려고 했는데
환경설정이 다른 것인지 빌드가 되지 않습니다.
코드를 확인해보니 윈도우에서 돌리신것 같은데 저의 환경은 우분투 기반이라 OpenCV 및 다른 헤더파일이 작동하지 않는 것 같습니다.
혹시 환경이 어떻게 되셨는지 알려주시면 너무 감사할 것 같습니다.

**Comment by HyunCello** [comment]
https://docs.opencv.org/master/db/df5/tutorial_linux_gcc_cmake.html 에서
OpenCV와 CMakeLists.txt 설정을 잘 따라하니 빌드 성공하였습니다!
답변 감사드립니다..! issue 닫겠습니다!
