### ISSUE TITLE
pcd 형식 파일 kitti  bin file형식으로 변환

### ISSUE THREAD

**Issue by ggomac** [SeunghwanByun/KITTI_PROJECTION#2]
안녕하세요 제가 pcd 형식 파일을 kitti bin file 형식으로 변환하고 싶은데 도움을 받을 수 있을까 해서 이렇게 글을 씁니다.
제 pcd 파일 형식이 아래와 같습니다.
```
# .PCD v0.7 - Point Cloud Data file format
VERSION 0.7
FIELDS x y z intensity
SIZE 4 4 4 1
TYPE F F F U
COUNT 1 1 1 1
WIDTH 116736
HEIGHT 1
VIEWPOINT 0 0 0 1 0 0 0
POINTS 116736
DATA binary
```

SeunghwanByun 님께서 만드신 bin2pcd.cpp 을 보니 kitti  bin file과 저희 pcd file 형식이 몇몇 부분이 다르다는 것을 알게 되었습니다. 
```
           me                                                     kitti 
fields :  x y z intensity                                   x y z
size : 4 4 4 1                                                 4 4 4
type: F F F U                                                 F F F
count: 1 1 1 1                                               없음
viewpoint: 0 0 0 1 0 0 0                                없음
data : binary                                                ascii
```
이러한 차이점이 있을 때 제 pcd file을 kitti bin file 로 변경할 수 있을까요?
변경이 가능하다면  kitti에 없는 부분들은 어떻게 해야 할지 알 수 있을까요?

**Comment by SeunghwanByun** [comment]
안녕하세요! 문의주신점 감사합니다.
우선 pcd 파일에는 다양한 헤더가 존재하기 때문에 제 코드에 있는 헤더랑 님이 갖고 계신 pcd 파일의 헤더가 다른 점은 충분히 있는 일입니다.
따라서, 현재 갖고 계신 헤더로도 kitti 데이터셋의 bin 파일로 변환이 가능하세요~
헤더 부분을 파싱하고 나면 그 다음부턴 x y z intensity 순으로 데이터가 읽힐겁니다. 헤더를 제외하고 순수 데이터 값만 가지고 binary file을 만드신다면 kitti bin file로 만드실 수 있으실 겁니다 !

**Comment by ggomac** [comment]
옙, 감사합니다!
